In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import np_utils
from keras.utils import load_img, img_to_array
from sklearn.metrics import classification_report

import os

import pandas as pd
import numpy as np
from numpy import asarray
import cv2

import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [85]:
from PIL import Image
path = "C:/Users/prash/My Drive/Colab Notebooks/Images/Capital/D_02.png"
im = Image.open(path)
im.show()

In [86]:
img = Image.open(path)
img = load_img(path, target_size=(28, 28))
img= img.convert('1')
x = asarray(img)


#x /= 255
x = np.expand_dims(x, axis=0)

#images = np.vstack([x])


In [87]:
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(1, 28, 28)


In [88]:
#x = np.where(x==' ', ',' , x)
x = np.where(x=='True', 1, x)

C:\Users\prash\AppData\Local\Temp\ipykernel_97080\3883391819.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  x = np.where(x=='True', 1, x)


In [89]:
np.set_printoptions(linewidth = 350)
print(x)

[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1]
  [1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1

In [90]:
print(type(x))

<class 'numpy.ndarray'>


In [91]:
final_array = x.tolist()

In [92]:
print(final_array)

[[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 

In [93]:
type(final_array)

list

In [94]:
temp_model_name = tf.keras.models.load_model("C:/Users/prash/My Drive/Colab Notebooks/TensorFlow/OCR_MODEL.h5")

In [95]:
ABC = temp_model_name.predict(final_array)

1/1 [==============================] - 0s 233ms/step


In [96]:
print(ABC)

[[7.78394751e-04 7.24413880e-08 2.78401390e-12 6.17305859e-16 3.09767511e-12 5.84701883e-13 3.31289106e-04 1.59204863e-08 5.70318662e-07 5.84610431e-13 9.17193610e-09 9.14778775e-06 6.03420025e-09 3.00294894e-04 1.38722849e-03 4.93318915e-01 2.59975739e-08 9.48414041e-08 1.61273341e-08 3.26835270e-09 4.12819498e-14 1.68676691e-13 1.92507753e-13
  5.34864947e-12 1.74381976e-09 1.27225980e-10 8.52009782e-12 3.09191388e-12 6.98033129e-16 1.35253225e-10 1.44234349e-07 6.05746891e-06 1.00808120e-06 1.14889723e-07 6.84622592e-07 1.04648964e-02 2.66502033e-12 4.26675778e-11 4.67025484e-06 1.84177846e-08 4.26714793e-02 1.03048687e-05 1.76916793e-12 1.32330555e-08 1.75973831e-08 3.42661679e-01
  3.90140922e-03 1.62325014e-05 1.46292034e-04 1.83292286e-04 4.18576155e-12 2.68390865e-09 9.68959284e-07 2.06403517e-09 9.67100635e-02 8.31128083e-11 2.97641634e-11 6.01571015e-09 1.22350219e-09 1.71418695e-12 3.33084706e-08 2.33648116e-13 4.45894148e-05 4.38967265e-11 7.97397703e-09 9.21827237e-09 2.56

In [97]:
print(ABC.max())
max = ABC[0].max()

0.49331892


In [98]:
ABC=ABC.tolist()

In [99]:
#index = classes_01[0].index(classes[0].max())

In [100]:
index = ABC[0].index(max)
index

15

In [101]:
labelNames = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[']

print(labelNames)


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[']


In [102]:
print(len(labelNames))
print(labelNames[index])

85
f
